# This is a basic workflow that is manually triggered

name: back Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    paths:
      - server/**
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
       # 检出代码到工作目录 
      - name: Checkout code
        uses: actions/checkout@v2
      # 登录到 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # 构建并推送 Docker 镜像
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./server/dockerfile
          push: true
          tags: fangchenjia/rf4-community-back:latest
      - name: Deploy to Docker
        uses: appleboy/ssh-action@master
        with:
          host: 110.42.213.115
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker stop rf4-community-back-server || true
            docker stop rf4-community-back-admin || true
            docker rm rf4-community-back-server || true
            docker rm rf4-community-back-admin || true
            docker rmi fangchenjia/rf4-community-back || true
            docker pull fangchenjia/rf4-community-back
            docker run -d -p 3004:3004 -v /var/log/rf4-community/server:/logs -v /var/apps/rf4-community/.env.prod:/app/.env.prod --name rf4-community-back-server fangchenjia/rf4-community-back
            docker run -d -p 3003:3003 -v /var/log/rf4-community/admin:/logs -v /var/apps/rf4-community/.env.prod:/app/.env.prod --name rf4-community-back-admin fangchenjia/rf4-community-back npm run start:prod:admin

  
