# This is a basic workflow that is manually triggered

name: front Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    paths:
      - web/**
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
       # 检出代码到工作目录 
      - name: Checkout code
        uses: actions/checkout@v2
      # 安装 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      # 安装项目依赖
      - name: Install dependencies
        run: |
          cd web/
          npm install
       # 构建前端项目
      - name: Build project
        run: |
          cd web/
          npm run build --page=pc
          npm run build --page=mobile
          npm run build --page=admin
      # 登录到 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # 构建并推送 Docker 镜像
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./web/dockerfile
          push: true
          tags: fangchenjia/rf4-community-front:latest
      - name: Deploy to Docker
        uses: appleboy/ssh-action@master
        with:
          host: 60.204.153.176
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker stop rf4-community-front || true
            docker rm rf4-community-front || true
            docker rmi fangchenjia/rf4-community-front || true
            docker pull fangchenjia/rf4-community-front
            docker run -d -p 8081:80 --name rf4-community-front fangchenjia/rf4-community-front

  
